# Generated by Django 4.1.5 on 2023-08-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
